---
- name: Install cower dependencies
  pacman: name=curl state=present
  pacman: name=openssl state=present
  pacman: name=pacman state=present
  pacman: name=yajl state=present
  pacman: name=perl state=present

- name: Install AUR helper, cower
  git: >
       repo=https://github.com/falconindy/cower.git
       dest=/usr/local/src/cower
- command: make install
  args:
    chdir: /usr/local/src/cower
    creates: /usr/bin/cower

- name: Install pacaur dependencies
  pacman: name=expac state=present

- name: Install AUR helper, pacaur
  git: >
       repo=https://github.com/rmarquis/pacaur
       dest=/usr/local/src/pacaur
- command: install -D pacaur /usr/bin/pacaur -o root -g root -m 0755
  args:
    chdir: /usr/local/src/pacaur
    creates: /usr/bin/pacaur
- command: >
           install -D config /etc/xdg/pacaur/config -o root -g root -m 0644
  args:
    chdir: /usr/local/src/pacaur
    creates: /etc/xdg/pacaur/config
- command: >
           install -D bash.completion /usr/share/bash-completion/completions
           -o root -g root -m 0644
  args:
    chdir: /usr/local/src/pacaur
    creates: /usr/share/bash-completion/completions
- command: >
           install -D zsh.completion
           /usr/local/share/zsh/site-functions/_pacaur
           -o root -g root -m 0644
  args:
    chdir: /usr/local/src/pacaur
    creates: /usr/local/share/zsh/site-functions/_pacaur
