---
- hosts: vps
  gather_facts: true

- hosts: fileserver
  roles:
          #    - packages
    - autossh_tunnel

      #- host: vps
      #  roles:
      #    - sshfs_mount
      #      mount_src: /zdata
      #      mount_host: localhost 
      #      mount_port: 9000
      #      dest: /zdata

