---
- name: Install sudo
  pacman:
    name: sudo
    state: present
  tags:
    - sudo
- name: Create sudo group
  group:
    name: sudo
    state: present
  tags:
    - sudo
- name: Add user to sudo group
  user:
    name: '{{ user.name }}'
    groups: sudo
    append: yes
  tags:
    - sudo
- name: Enable sudo group in sudoers
  replace:
    dest: /etc/sudoers
    regexp: '^#\s*%sudo\s+ALL=\(ALL\)\s+ALL'
    replace: '%sudo ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  tags:
    - sudo
