---
- name: Update everything in homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install managed python install
  homebrew: name=python state=present

- name: Install midnight commander
  homebrew: name=mc state=present

- name: Install iTerm
  homebrew_cask: name=iterm2 state=present

- name: Install Node.js
  homebrew: name=nodejs state=present

- name: Install OSX FUSE
  homebrew_cask: name=osxfuse state=present

- name: Install sshfs
  homebrew_cask: name=sshfs state=present

- name: Install Atom.io editor
  homebrew_cask: name=atom state=present
