---
- include: scm.yml
- include: wireshark.yml
- include: vagrant.yml
- include: virtualbox.yml

#- name: IT automation
#  pacman: name=ansible state=present
#
#- name: Screen recording (still/video)
#  pacman: name=scrot state=present
#  pacman: name=recordmydesktop state=present
#  pacman: name=gtk-recordmydesktop state=present
