---
- hosts: home
  sudo: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: browsers, tags: ['firefox', 'chromium'] }
    - { role: x }
    - { role: filesystem, tags: ['filesystem'] }
    - { role: archivers, tags: ['archivers'] }
    - { role: editors, tags: ['editors'] }
    - { role: sound, tags: ['sound'] }
    - { role: networking, tags: ['networking'] }
    - { role: awesome, tags: ['windowmanager'] }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: audio, tags: ['audio'] }
    - { role: video, tags: ['video'] }
    - { role: graphics, tags: ['graphics'] }
    - { role: games, tags: ['games'] }
    - { role: office, tags: ['office'] }
    - { role: docker, tags: ['docker'] }
    - { role: development, tags: ['development'] }
