---
- name: Set up laptop
  hosts: desktop
  user: root

## This assumes that install has made it completely through.
# However, mistakes can be made, correct any of them

  roles:
    - arch_install_verify
    - common
    - gui
    - development
    - aur_helper
    - office
    - media
